language: julia
os: linux
dist: bionic
julia:
  - 1.4.1

notifications:
  email: false

script: julia --project -e '
  using Pkg;
  Pkg.build();
  Pkg.test()'

jobs:
  include:
    - stage: Documentation
      julia: 1.4.1
      os: linux
      script: julia --project -e '
          using Pkg;
          Pkg.instantiate();
          include("docs/make.jl")'
      after_success: skip